### ISSUE TITLE
sed: 1: ".env": invalid command code .

### ISSUE THREAD

**Issue by songproducer** [marigold-dev/training-nft-1#7]
I'm not sure if I've entered the command in package.json correctly.
<img width="1424" alt="Screen Shot 2022-12-30 at 10 21 55 pm" src="https://user-images.githubusercontent.com/597346/210080417-d5d1ad3e-69d9-4085-a067-6380074a2b24.png">

**Comment by zamrokk** [comment]
Do you have a Mac ?

in this case, you have a note to change the sed command on the training

> Note : On `Mac` :green_apple:, `sed` does not work as Unix, change the start script on package.json to
> `                 "start": "if test -f .env; then sed -i '' \"s/\\(REACT_APP_CONTRACT_ADDRESS *= *\\).*/\\1$(jq -r 'last(.tasks[]).output[0].address' ../.taq/testing-state.json)/\" .env ; else jq -r '\"REACT_APP_CONTRACT_ADDRESS=\" + last(.tasks[]).output[0].address' ../.taq/testing-state.json > .env ; fi && react-app-rewired start",                                                  `

**Comment by zamrokk** [comment]
the difference is `sed -i ''`         (double single quote)

**Comment by songproducer** [comment]
Hi! Thanks, yes I have a Mac. I looked at my package.json and saw that the single quotes were magically there. I also needed to adjust the path for .taq directory (it was referencing the parent directory. Now I'm getting this error:

/bin/sh: react-app-rewired: command not found

Do I need to install this somehow?

**Comment by zamrokk** [comment]
if you have copied the boilerplate app , so you should have on dev dependencies the react rewired

  "devDependencies": {
...
    "react-app-rewired": "^2.2.1",

**Comment by zamrokk** [comment]
if you don't have it, you can install it manually : 
- if it is declared but not installed : yarn install
- if it is not declared and not installed : yarn add -D react-app-rewired

**Comment by songproducer** [comment]
I get:
 ```
 code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/leotreasure/nft1/training/node_modules/react-app-rewired/scripts/utils/paths.js',
    '/Users/leotreasure/nft1/training/node_modules/react-app-rewired/scripts/utils/dependRequire.js',
    '/Users/leotreasure/nft1/training/node_modules/react-app-rewired/bin/index.js'
  ]
}
```

**Comment by zamrokk** [comment]
Don't have a mac but found similar issue on chinese website : 

`npm i --legacy-peer-deps`

found this also that try to explain : https://stackoverflow.com/questions/66239691/what-does-npm-install-legacy-peer-deps-do-exactly-when-is-it-recommended-wh

**Comment by songproducer** [comment]
I get 8 high severity vulnerabilities

So I run:
npm audit fix --legacy-peer-deps --force
but get
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "from" argument must be of type string. Received undefined

Appreciate your help - I think I need to try to install linux on Mac

**Comment by zamrokk** [comment]
The boilerplate has been created using this example here :

https://github.com/marigold-dev/training-dapp-1#step-1--create-react-app

Maybe it can hep you to fix react issues.
On of my colleague tested on a Mac and had no issue with this training :/

I don't understand why you have this issue. why version of MacOs do you have ? Which version of nodejs ?

**Comment by songproducer** [comment]
Hi, I think I was following a tutorial before but now after some time away I tried to run in the solution folder and things are working a bit better.

My Mac version is 12.6.2 and Node version is v18.12.1

Now I need to install flextesa to generate an address on ghostnet but when I run

>taq install @taqueria/plugin-flextesa

I get:

>Your config.json file is invalid

Here is my config.json file:

```
{
    "language": "en",
    "contractsDir": "contracts",
    "artifactsDir": "artifacts",
    "contracts": {
        "nft.jsligo": {
            "sourceFile": "nft.jsligo",
            "hash": "5737454d4dd7c3947452a5d2003c30353b62f19a6d73f98ad830a187574b3751"
        }
    },
    "network": {
        "ghostnet": {
            "label": "ghostnet",
            "rpcUrl": "https://ghostnet.ecadinfra.com",
            "protocol": "PtLimaPtLMwfNinJi9rCfDPWea8dFgTZ1MeJ9f1m2SRic6ayiwW",
            "accounts": {
                "taqOperatorAccount": {
                    "publicKey": "edpkvGfYw3LyB1UcCahKQk4rF2tvbMUk8GFiTuMjL75uGXrpvKXhjn",
                    "publicKeyHash": "tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb",
                    "privateKey": "edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq"
                }
            }
        }
    },
    "sandbox": {
        "local": {
            "label": "Local Tezos Sandbox",
            "rpcUrl": "http://localhost:20000",
            "protocol": "PtLimaPtLMwfNinJi9rCfDPWea8dFgTZ1MeJ9f1m2SRic6ayiwW"
        }
    },
    "environment": {
        "default": "development",
        "development": {
            "networks": [],
            "sandboxes": [
                "local"
            ]
        },
        "testing": {
            "networks": [
                "ghostnet"
            ],
            "sandboxes": [],
            "aliases": {
                "nft": {
                    "address": "KT1QTwcQWpf4MRM5sjoGC6ASn4Y5fJNsTqWd"
                }
            }
        }
    },
    "accounts": {
        "bob": "3_000_000_000",
        "alice": "3_000_000_000",
        "john": "3_000_000_000",
        "jane": "3_000_000_000",
        "joe": "3_000_000_000"
    },
    "plugins": [
        {
            "name": "@taqueria/plugin-core",
            "type": "npm"
        },
        {
            "name": "@taqueria/plugin-ligo",
            "type": "npm"
        },
        {
            "name": "@taqueria/plugin-taquito",
            "type": "npm"
        },
        {
            "name": "@taqueria/plugin-contract-types",
            "type": "npm"
        }
    ],
    "projectDir": "/home/zamrokk/training-nft-1/solution",
    "configFile": "/home/zamrokk/training-nft-1/solution/.taq/config.json",
    "hash": "5d4b61c2bd96382c7b128e39739c29f6917f3b94694be07c6e81aa7d92df129f"
}
```

**Comment by zamrokk** [comment]
To be admin, you just need to change the initial storage and chnage the field admin by your own user. Or, just keep alice and override the taqueria user with alice settings (is what I do)

**Comment by zamrokk** [comment]
Another person did the full traiing on Mac with no issue so far. Maybe on the npm issue, you should remove the node_module folder and try to do a `yarn install` to reinstall all deps
